Overhaul emails section
ClouDesire/docusaurus pull request #170
Opened 2021-10-06 15:21 UTC by malteo

https://github.com/ClouDesire/support/issues/5684

2021-10-14 07:27 UTC, pimuzzo submitted a review, later dismissed

2021-10-15 14:38 UTC, gionn commented
ho fixato i title

![image](https://user-images.githubusercontent.com/71768/137505280-8e1f3c76-bdc8-4512-a4c0-168f65bc2e7f.png)

2021-10-15 14:48 UTC, pimuzzo requested changes

2021-10-15 14:48 UTC, pimuzzo commented on docs/emails.md
> +Once the customer order a product the following email is sent.
```suggestion
Once the customer orders a product the following email is sent.
```

2021-10-15 15:13 UTC, gionn approved these changes

2021-10-15 15:16 UTC, pimuzzo approved these changes

2021-10-18 08:38 UTC, merged