Add typescript client page
ClouDesire/docusaurus pull request #239
Opened 2022-03-29 14:34 UTC by malteo

https://github.com/ClouDesire/support/issues/6361

2022-03-29 14:36 UTC, AndreaVecchi approved these changes, later dismissed

2022-03-30 14:40 UTC, manuelmazzuola requested changes

2022-03-30 14:40 UTC, manuelmazzuola commented on docs/api-typescript.md
> +Install required packages, for example
```suggestion
Install the required packages, for example:
```

2022-03-30 14:40 UTC, manuelmazzuola commented on docs/api-typescript.md
> +You can find a TypeScript client on our [Nexus Repository](https://nexus.cloudesire.com/#browse/browse:cloudesire-npm-public).
```suggestion
You can find a TypeScript client on our [NPM Repository](https://nexus.cloudesire.com/#browse/browse:cloudesire-npm-public).
```

2022-03-30 14:40 UTC, manuelmazzuola commented on docs/api-typescript.md
> +const url = '<cmw_api_url>';
```suggestion
const url = '<cloudesire_api_url>';
```

2022-03-30 14:43 UTC, manuelmazzuola requested changes

2022-03-30 14:43 UTC, manuelmazzuola commented on docs/api-typescript.md
> +You can find a TypeScript client on our [NPM Repository](https://nexus.cloudesire.com/#browse/browse:cloudesire-npm-public).
```suggestion
You can find the TypeScript clients on our NPM Repository: `https://nexus.cloudesire.com/repository/cloudesire-npm-public/`.  
Click [here](https://nexus.cloudesire.com/#browse/browse:cloudesire-npm-public) to browse the available packages.
```

2022-03-30 14:52 UTC, malteo commented on docs/api-typescript.md
> +You can find a TypeScript client on our [NPM Repository](https://nexus.cloudesire.com/#browse/browse:cloudesire-npm-public).
da sloggato va usato l'URL con `#browse`

inoltre mi piace l'uso degli hyperlink

2022-03-30 14:54 UTC, manuelmazzuola commented on docs/api-typescript.md
> +You can find a TypeScript client on our [NPM Repository](https://nexus.cloudesire.com/#browse/browse:cloudesire-npm-public).
ma non è quello il repository npm

2022-03-30 14:59 UTC, malteo commented on docs/api-typescript.md
> +You can find a TypeScript client on our [NPM Repository](https://nexus.cloudesire.com/#browse/browse:cloudesire-npm-public).
capito, ho lasciato l'hyperlink alla versione browsabile e ho esplicitato l'URL del repository npm

2022-03-31 07:24 UTC, manuelmazzuola approved these changes

2022-03-31 07:24 UTC, merged