Add blog post about caching and local circleci build
ClouDesire/docusaurus pull request #24
Opened 2018-09-27 13:39 UTC by manuelmazzuola

https://github.com/ClouDesire/support/issues/1828

2018-09-27 14:10 UTC, malteo requested changes

2018-09-27 14:10 UTC, malteo commented on website/blog/2018-09-26-circleci-ci-cache-proxy.md
> +At Cloudesire a couple of years ago we decided to switch from Jenkins to CircleCI. First of all, because we are lazy to self-maintain a server and secondly because CircleCI seemed a great build servi
seemed like

2018-09-27 14:10 UTC, malteo commented on website/blog/2018-09-26-circleci-ci-cache-proxy.md
> +A fast setup solution I currently use is to proxy docker to a local nginx or squid container that acts as cache layer.
let's focus on nginx, remove squid

add links to the docker and nginx pages?

2018-09-27 14:10 UTC, malteo commented on website/blog/2018-09-26-circleci-ci-cache-proxy.md
> +`$ docker run --name nginx-cache -d manuelmazzuola/nginx-cache` and get the internal IP by inspecting it with `docker inspect nginx-cache | grep IPAddress`
give these commands their own boxes with the new line / four leading spaces format

2018-09-27 14:10 UTC, malteo commented on website/blog/2018-09-26-circleci-ci-cache-proxy.md
> +Create or edit the file `~/.docker/config.json` and change it according to the following conf where `{IP}` is the internal IP of the cache container:
s/conf/configuration

2018-09-27 14:10 UTC, malteo commented on website/blog/2018-09-26-circleci-ci-cache-proxy.md
> +and test it by running the following twice `docker run --rm alpine/httpie --print=hH GET unpkg.com/react@16/umd/react.development.js Cache-Control:no-cache`, the first response will contains `X-Cache
same as above for the command

2018-09-27 14:10 UTC, malteo commented on website/blog/2018-09-26-circleci-ci-cache-proxy.md
> +But wait, why the file has been cached even if `Cache-Control:nocache` is present? Our `nginx-cache` container ignore all the caching headers because some build tools, like maven, add the `Cache-Cont
why was the file cached

2018-09-27 14:13 UTC, gionn commented on website/blog/2018-09-26-circleci-ci-cache-proxy.md
> +`$ docker run --name nginx-cache -d manuelmazzuola/nginx-cache` and get the internal IP by inspecting it with `docker inspect nginx-cache | grep IPAddress`
link to Dockerfile

2018-09-28 09:41 UTC, malteo approved these changes

2018-09-28 09:49 UTC, pimuzzo approved these changes

2018-09-28 09:50 UTC, gionn commented on website/blog/2018-09-26-circleci-ci-cache-proxy.md
> +At Cloudesire a couple of years ago we decided to switch from Jenkins to CircleCI. First of all, because we are lazy to self-maintain a server and secondly because CircleCI seemed like a great build
s/and they were very generous with their limits/and their pricing affodable

2018-09-28 12:52 UTC, gionn approved these changes

2018-09-28 13:00 UTC, pimuzzo approved these changes

2018-09-28 13:44 UTC, merged