Move Pricing models section in a new page
ClouDesire/docusaurus pull request #43
Opened 2019-03-15 07:59 UTC by gionn

2019-03-18 11:21 UTC, pimuzzo commented on docs/onboarding-extra-resources.md
> +the application (for example, a 10-days pack of Technical Support, hardware
```suggestion
the application (for example, a 10-days pack of technical support, hardware
```

2019-03-18 11:23 UTC, pimuzzo commented on docs/onboarding-extra-resources.md
> +price per unit withing a range, while volume pricing defines a price for all
```suggestion
price per unit within a range, while volume pricing defines a price for all
```

2019-03-18 11:28 UTC, pimuzzo commented on docs/billing.md
> +the sum of all the discounted prices of all the _products plans_ attached to
```suggestion
the sum of all the discounted prices of all the _product plans_ attached to
```

2019-03-18 11:32 UTC, pimuzzo commented on docs/onboarding-extra-resources.md
> +* _Step_: should be greater than 1. Decide which are the effective quantities
```suggestion
* _Step_: should be greater than or equal to 1. Decide which are the effective quantities
```

2019-03-18 11:42 UTC, pimuzzo commented on docs/onboarding-plans.md
> +product. Examples are a 10-days pack of Technical Support, some hardware
```suggestion
product. Examples are a 10-days pack of technical support, some hardware
```

2019-03-18 11:44 UTC, pimuzzo commented on docs/pricing-models.md
> +example, you can add extra resources to your product LINK), but the choice of
missing link! :fire:

2019-03-18 11:45 UTC, pimuzzo commented on docs/pricing-models.md
> +catalog. Select the product, then "_Edit_" and go to the "_Plans_" tab.You can
```suggestion
catalog. Select the product, then "_Edit_" and go to the "_Plans_" tab. You can
```

2019-03-21 10:09 UTC, malteo requested changes

2019-03-21 10:09 UTC, malteo commented on docs/billing.md
> +* every backup plan includes to a maximum number of backups executions
this is not clear

2019-03-21 10:09 UTC, malteo commented on docs/api-product.md
> +Catalog, as described in the [onboarding](onboarding.md) section.
```suggestion
Catalog, as described in the [onboarding section](onboarding.md).
```

2019-03-21 10:09 UTC, malteo commented on docs/glossary.md
> +## Extra-Resources
no need for the hyphen

```suggestion
## Extra Resources
```

2019-03-21 10:09 UTC, malteo commented on docs/glossary.md
> +Go to [Extra-Resources](onboarding-extra-resources.md) section.
```suggestion
Go to [Extra Resources section](onboarding-extra-resources.md).
```

2019-03-21 10:09 UTC, malteo commented on website/i18n/en.json
> +      },
I still think there's no need for the hyphen in "Extra resources"

plus be consistent with the capital letters

2019-03-21 13:52 UTC, manuelmazzuola approved these changes

2019-03-21 14:00 UTC, malteo approved these changes

2019-03-21 14:02 UTC, merged