Document customer cloud credentials
ClouDesire/docusaurus pull request #59
Opened 2019-07-19 08:45 UTC by gionn

2019-07-22 07:36 UTC, pimuzzo requested changes

2019-07-22 07:36 UTC, pimuzzo commented on docs/customer-cloud-credentials.md
> +  `https://management.azure.com/subscriptions/<subscription id>`
```suggestion
  `https://management.azure.com/subscriptions/<subscription-id>`
```

2019-07-22 08:36 UTC, manuelmazzuola approved these changes

2019-07-22 14:34 UTC, pimuzzo approved these changes

2019-07-23 09:27 UTC, malteo approved these changes

2019-07-23 09:42 UTC, merged