Add API products (WIP)
ClouDesire/docusaurus pull request #8
Opened 2018-04-24 10:51 UTC by gionn

2018-04-24 13:54 UTC, AndreaVecchi commented on docs/api-product.md
> +When a consumer send a request to the API, an additional set of HTTP headers is
"sends"

2018-04-24 13:55 UTC, AndreaVecchi commented on docs/api-product.md
> +* `X-Consumer-Custom-ID`: the id of the user that bought the subscription
which

2018-04-24 13:56 UTC, AndreaVecchi commented on docs/api-product.md
> +possible to define a prepaid pricing model based on the actual HTTP calls
current

2018-04-24 13:57 UTC, AndreaVecchi commented on docs/api-product.md
> +For every HTTP call that needs to be billed, create a resource with:
link to "extra resources"

2018-05-10 14:39 UTC, malteo requested changes

2018-05-10 14:39 UTC, malteo commented on docs/api-product.md
> +In this section it is presented how to onboard and start selling an API-based
This section describes how...

2018-05-10 14:39 UTC, malteo commented on docs/api-product.md
> +Secure access to the API is managed by the platform, generating an **unique
a unique

http://www.writersdigest.com/online-editor/a-before-consonants-and-an-before-vowels-is-not-the-rule

2018-05-10 14:39 UTC, malteo commented on docs/api-product.md
> +* `X-Consumer-Custom-ID`: the id of the user which bought the subscription
vogliamo specificare che è l'id del customer della *nostra* piattaforma?

2018-05-11 07:25 UTC, malteo approved these changes

2018-05-28 12:46 UTC, merged